<a href="https://colab.research.google.com/github/NadiiaDataAnalyst/A-real-world-analytics-internship-with-CRM-sales-data-exported-from-the-Prog-Academy-system.-/blob/main/%D0%A1%D1%82%D0%B0%D0%B6%D0%B8%D1%80%D0%BE%D0%B2%D0%BA%D0%B0_%D0%BE%D1%87%D0%B8%D1%89%D0%B5%D0%BD%D0%BD%D1%8F_%D0%B4%D0%B0%D0%BD%D0%B8%D1%85.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from google.colab import files

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
path = '/content/drive/MyDrive/crm_output_anonymized.csv'

In [ ]:
pd.set_option('display.max_columns', None)

In [ ]:
df = pd.read_csv(path,
                 sep=',',
                 quotechar='"',
                 encoding="utf-8-sig",
                 engine='python',
                 on_bad_lines='skip')
df

,ID,Lead title,Lead sale ₴,Respons. user,Created on,Created by,Modified on,Modified by,Closed at,Tags,Note,Note 2,Note 3,Note 4,Note 5,Lead stage,Pipeline,Fullname,Contact`s company,Contact respons. user,Lead's company,Work phone,Work DD phone,Mobile phone,Fax,Home phone,Other phone,Work email,Personal email,Other email,Telegram,Position,Skype,ICQ,Jabber,Google Talk,MSN,Other IM,Facebook URL,Пользовательское соглашение,Title,TRAF_SRC,TRAF_TYPE,ADV_CAMP,KEYWORD,TRAF_CONT,GOOGLE_ID,Upcoming Appointment,Оплата,Курс,Lead scoring,Название пакета,Язык,Комментарий,COURSE,UTM_ID,UTM_ADGROUP,FORMNAME,URL первого визита,utm_source,utm_medium,utm_campaign,utm_term,utm_content,Referrer,ip,hostname,city,region,country,loc,org,day_of_week,TRAF_SRC.1,GOOGLE_ID.1,TRAF_CONT.1,KEYWORD.1,ADV_CAMP.1,TRAF_TYPE.1,UTM_TARGET,REFERER,FORMID,TRANID,COOKIES,Вопрос 1,Вопрос 2,Вопрос 3,Вопрос 4,Вопрос 5,openstat_campaign,fbclid,yclid,gclid,gclientid,openstat_source,openstat_ad,from,openstat_service,utm_term.1,utm_source.1,referrer,utm_campaign.1,utm_medium.1,utm_content.1,utm_referrer,_ym_uid,_ym_counter,roistat,ga_utm;;;;;;;;;;;;;;;;;;
0,utm_source: meta;;;;;;;;;;;;;;;;;;,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,None,NaN,NaN,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,NaN,None,None,None,None,None,None,NaN,NaN,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,None,NaN,NaN,NaN,None,NaN,None,None,NaN,None,None,None,None,NaN,NaN,NaN,None
1,utm_medium: cpc;;;;;;;;;;;;;;;;;;,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,None,NaN,NaN,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,NaN,None,None,None,None,None,None,NaN,NaN,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,None,NaN,NaN,NaN,None,NaN,None,None,NaN,None,None,None,None,NaN,NaN,NaN,None
2,utm_campaign: HTTP+|+Data+Analytics+++безкошто...,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,None,NaN,NaN,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,NaN,None,None,None,None,None,None,NaN,NaN,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,None,NaN,NaN,NaN,None,NaN,None,None,NaN,None,None,None,None,NaN,NaN,NaN,None
3,utm_content: broad+interests+–+27.05;;;;;;;;;;...,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,None,NaN,NaN,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,NaN,None,None,None,None,None,None,NaN,NaN,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,None,NaN,NaN,NaN,None,NaN,None,None,NaN,None,None,None,None,NaN,NaN,NaN,None
4,utm_term: статика+6;;;;;;;;;;;;;;;;;;,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,None,NaN,NaN,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,NaN,None,None,None,None,None,None,NaN,NaN,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,None,NaN,NaN,NaN,None,NaN,None,None,NaN,None,None,None,None,NaN,NaN,NaN,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5881,- Email: zfbirsutd137@gmail.com;;;;;;;;;;;...,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,None,NaN,NaN,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,NaN,None,None,None,None,None,None,NaN,NaN,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,None,NaN,NaN,NaN,None,NaN,None,None,NaN,None,None,None,None,NaN,NaN,NaN,None
5882,59320181,Lead #59320181,0,Vasyl F.,06.04.2026 10:44:45,NaN,21.04.2026 19:01:01,Vasyl F.,21.04.2026 19:01:00,lang-ua,NaN,NaN,NaN,NaN,NaN,Закрыто и не реализовано (перестал отвечать в ...,Продажи,Hryhorii Moskalenko,NaN,Vasyl F.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Нет,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.886348e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,;;;;;;;;;;;;;;;;;;
5883,59318911,Lead #59318911,0,Natalia H.,06.04.2026 09:02:13,NaN,08.04.2026 11:04:27,Natalia H.,08.04.2026 11:04:00,lang-ru,NaN,NaN,NaN,NaN,NaN,Закрыто и не реализовано (перестал отвечать в ...,Продажи,Dmytro Moskalenko,NaN,Natalia H.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Нет,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,k6RHevbLAIlGpNoPvOoWdJj9lC9gBwLpXLUp9lCO0A3fB4...,6.294803e+08,NaN,NaN,NaN,NaN,тестировщик с нуля,google,NaN,Search - QA - EU,cpc,loc_interest_ms-__loc_physical_ms-9043353__dev...,NaN,NaN,NaN,NaN,;;;;;;;;;;;;;;;;;;
5884,;;;;;;;;;;;;;;;;;;,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,None,NaN,NaN,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,NaN,None,None,None,None,None,None,NaN,NaN,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,None,NaN,NaN,NaN,None,NaN,None,None,NaN,None,None,None,None,NaN,NaN,NaN,None
5885,але в нього зараз немає компа для навчання,тільки планшет;;;;;;;;;;;;;;;;;;,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,None,NaN,NaN,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,NaN,None,None,None,None,None,None,NaN,NaN,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,None,NaN,NaN,NaN,None,NaN,None,None,NaN,None,None,None,None,NaN,NaN,NaN,None

In [ ]:
df['ID'].unique()

array(['63408688,[NEW] free-data-analytics — /ua/free/data-analytics,0,Vasyl F.,04.06.2026 11:37:01,,04.06.2026 11:39:26,Ivan M.,not closed,,"\'=== First Touch ===;;;;;;;;;;;;;;;;;;',
       'utm_source: meta;;;;;;;;;;;;;;;;;;',
       'utm_medium: cpc;;;;;;;;;;;;;;;;;;', ...,
       'але в нього зараз немає компа для навчання',
       'нагадати про навчання на початку червня, має вирішити це питання",не встиг ще подивитись пробне,"веб дивився, але до цього проходив схожий в GOIT і для нього було скучно;;;;;;;;;;;;;;;;;;',
       'для себе цікавився, відправив пробне, можливо зацікавить",,,Получил материалы,Продажи,Yulia Moroz,,Vasyl F.,,,,+380933183619,,,,,eiyoxxtsz458@outlook.com,,,,,,,,,,,No,,,,,,,,,Нет,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,https://ai-web-ua.prog.academy/,,,,,,,,;;;;;;;;;;;;;;;;;;'],
      dtype=object)

In [ ]:
print(df.columns.tolist())

['ID', 'Lead title', 'Lead sale ₴', 'Respons. user', 'Created on', 'Created by', 'Modified on', 'Modified by', 'Closed at', 'Tags', 'Note', 'Note 2', 'Note 3', 'Note 4', 'Note 5', 'Lead stage', 'Pipeline', 'Fullname', 'Contact`s company', 'Contact respons. user', "Lead's company", 'Work phone', 'Work DD phone', 'Mobile phone', 'Fax', 'Home phone', 'Other phone', 'Work email', 'Personal email', 'Other email', 'Telegram', 'Position', 'Skype', 'ICQ', 'Jabber', 'Google Talk', 'MSN', 'Other IM', 'Facebook URL', 'Пользовательское соглашение', 'Title', 'TRAF_SRC', 'TRAF_TYPE', 'ADV_CAMP', 'KEYWORD', 'TRAF_CONT', 'GOOGLE_ID', 'Upcoming Appointment', 'Оплата', 'Курс', 'Lead scoring', 'Название пакета', 'Язык', 'Комментарий', 'COURSE', 'UTM_ID', 'UTM_ADGROUP', 'FORMNAME', 'URL первого визита', 'utm_source', 'utm_medium', 'utm_campaign', 'utm_term', 'utm_content', 'Referrer', 'ip', 'hostname', 'city', 'region', 'country', 'loc', 'org', 'day_of_week', 'TRAF_SRC.1', 'GOOGLE_ID.1', 'TRAF_CONT.1', 'KEYWORD.1', 'ADV_CAMP.1', 'TRAF_TYPE.1', 'UTM_TARGET', 'REFERER', 'FORMID', 'TRANID', 'COOKIES', 'Вопрос 1', 'Вопрос 2', 'Вопрос 3', 'Вопрос 4', 'Вопрос 5', 'openstat_campaign', 'fbclid', 'yclid', 'gclid', 'gclientid', 'openstat_source', 'openstat_ad', 'from', 'openstat_service', 'utm_term.1', 'utm_source.1', 'referrer', 'utm_campaign.1', 'utm_medium.1', 'utm_content.1', 'utm_referrer', '_ym_uid', '_ym_counter', 'roistat', 'ga_utm;;;;;;;;;;;;;;;;;;']

In [ ]:
print(df.isnull().sum())

ID                             0
Lead title                  6984
Lead sale ₴                 7027
Respons. user               7040
Created on                  7040
                            ...
utm_referrer                7208
_ym_uid                     7221
_ym_counter                 7221
roistat                     7221
ga_utm;;;;;;;;;;;;;;;;;;    7044
Length: 109, dtype: int64

In [ ]:
print(df.shape)

(7221, 109)

In [ ]:
print(df.dtypes)

ID                           object
Lead title                   object
Lead sale ₴                  object
Respons. user                object
Created on                   object
                             ...
utm_referrer                 object
_ym_uid                     float64
_ym_counter                 float64
roistat                     float64
ga_utm;;;;;;;;;;;;;;;;;;     object
Length: 109, dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7221 entries, 0 to 7220
Columns: 109 entries, ID to ga_utm;;;;;;;;;;;;;;;;;;
dtypes: float64(49), object(60)
memory usage: 6.0+ MB

In [ ]:
df['Lead sale ₴'] = pd.to_numeric(df['Lead sale ₴'], errors='coerce')

In [ ]:
df['Lead sale ₴'].sum()

np.float64(5000.0)

In [ ]:
df_clean = df[pd.to_numeric(df['ID'], errors='coerce').notna()]
df_clean

,ID,Lead title,Lead sale ₴,Respons. user,Created on,Created by,Modified on,Modified by,Closed at,Tags,Note,Note 2,Note 3,Note 4,Note 5,Lead stage,Pipeline,Fullname,Contact`s company,Contact respons. user,Lead's company,Work phone,Work DD phone,Mobile phone,Fax,Home phone,Other phone,Work email,Personal email,Other email,Telegram,Position,Skype,ICQ,Jabber,Google Talk,MSN,Other IM,Facebook URL,Пользовательское соглашение,Title,TRAF_SRC,TRAF_TYPE,ADV_CAMP,KEYWORD,TRAF_CONT,GOOGLE_ID,Upcoming Appointment,Оплата,Курс,Lead scoring,Название пакета,Язык,Комментарий,COURSE,UTM_ID,UTM_ADGROUP,FORMNAME,URL первого визита,utm_source,utm_medium,utm_campaign,utm_term,utm_content,Referrer,ip,hostname,city,region,country,loc,org,day_of_week,TRAF_SRC.1,GOOGLE_ID.1,TRAF_CONT.1,KEYWORD.1,ADV_CAMP.1,TRAF_TYPE.1,UTM_TARGET,REFERER,FORMID,TRANID,COOKIES,Вопрос 1,Вопрос 2,Вопрос 3,Вопрос 4,Вопрос 5,openstat_campaign,fbclid,yclid,gclid,gclientid,openstat_source,openstat_ad,from,openstat_service,utm_term.1,utm_source.1,referrer,utm_campaign.1,utm_medium.1,utm_content.1,utm_referrer,_ym_uid,_ym_counter,roistat,ga_utm;;;;;;;;;;;;;;;;;;
44,63407150,Lead #63407150,0.0,Vasyl F.,04.06.2026 09:29:40,NaN,04.06.2026 10:06:57,Vasyl F.,not closed,NaN,NaN,NaN,NaN,NaN,NaN,Заявка,Продажи,Serhii Moskalenko,NaN,Vasyl F.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Нет,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,;;;;;;;;;;;;;;;;;;
575,63349437,380734324457,0.0,Oksana B.,03.06.2026 12:33:46,NaN,03.06.2026 12:36:49,Oksana B.,03.06.2026 12:36:00,Ringostat Automation,NaN,NaN,NaN,NaN,NaN,Закрыто и не реализовано (спам),Продажи,Mykola Kravchenko,NaN,Oksana B.,NaN,NaN,NaN,+380979402003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Нет,NaN,C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,;;;;;;;;;;;;;;;;;;
615,63348663,Lead #63348663,0.0,Oksana B.,03.06.2026 11:40:29,NaN,03.06.2026 14:31:42,Oksana B.,not closed,lang-ru,NaN,NaN,NaN,NaN,NaN,Принимает решение,Продажи,Nadiia Bondarenko,NaN,Oksana B.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Monobank частями,QA-тестирование,A,NaN,RU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.849458e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,;;;;;;;;;;;;;;;;;;
1226,63300203,Lead #63300203,0.0,Natalia H.,02.06.2026 13:14:24,NaN,03.06.2026 13:55:08,Natalia H.,03.06.2026 13:55:00,lang-ua,NaN,NaN,NaN,NaN,NaN,Закрыто и не реализовано (перестал отвечать в ...,Продажи,Nadiia Zakharchenko,NaN,Natalia H.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Нет,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,;;;;;;;;;;;;;;;;;;
1712,63234121,Lead #63234121,0.0,Oksana B.,31.05.2026 16:10:06,NaN,03.06.2026 16:55:37,Oksana B.,not closed,NaN,NaN,NaN,NaN,NaN,NaN,Получил материалы,Продажи,Iryna Melnyk,NaN,Oksana B.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Нет,NaN,B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,;;;;;;;;;;;;;;;;;;
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5864,59397093,Lead #59397093,0.0,Oksana B.,07.04.2026 16:19:02,NaN,07.04.2026 23:03:28,Oksana B.,07.04.2026 23:03:00,NaN,NaN,NaN,NaN,NaN,NaN,Закрыто и не реализовано (спам),Продажи,Halyna Boychuk,NaN,Oksana B.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Нет,NaN,C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,;;;;;;;;;;;;;;;;;;
5868,59353455,380960149495,0.0,Natalia H.,06.04.2026 20:41:51,NaN,07.04.2026 10:32:41,Natalia H.,07.04.2026 10:32:00,Ringostat Automation,співпраця,NaN,NaN,NaN,NaN,Закрыто и не реализовано (спам),Продажи,Andrii Boychuk,NaN,Natalia H.,NaN,NaN,NaN,+380632084410,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Нет,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,;;;;;;;;;;;;;;;;;;
5869,59353143,Lead #59353143,0.0,Oksana B.,06.04.2026 20:33:30,NaN,13.04.2026 16:54:48,Oksana B.,13.04.2026 16:54:00,lang-ru,NaN,NaN,NaN,NaN,NaN,Закрыто и не реализовано (не актуально),Продажи,Larysa Kovalenko,NaN,Oksana B.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Нет,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,v6mQmVCllbKtexRgp-NwJJJCNn2VN5b6W8kLP-BgZY8srA...,2.797536e+08,NaN,NaN,NaN,NaN,курс data engineer,google,NaN,Search - Курс Data Analytics - EU,cpc,loc_interest_ms-__loc_physical_ms-9197880__dev...,NaN,NaN,NaN,NaN,;;;;;;;;;;;;;;;;;;
5882,59320181,Lead #59320181,0.0,Vasyl F.,06.04.2026 10:44:45,NaN,21.04.2026 19:01:01,Vasyl F.,21.04.2026 19:01:00,lang-ua,NaN,NaN,NaN,NaN,NaN,Закрыто и не реализовано (перестал отвечать в ...,Продажи,Hryhorii Moskalenko,NaN,Vasyl F.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Нет,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.886348e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,;;;;;;;;;;;;;;;;;;
5883,59318911,Lead #59318911,0.0,Natalia H.,06.04.2026 09:02:13,NaN,08.04.2026 11:04:27,Natalia H.,08.04.2026 11:04:00,lang-ru,NaN,NaN,NaN,NaN,NaN,Закрыто и не реализовано (перестал отвечать в ...,Продажи,Dmytro Moskalenko,NaN,Natalia H.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Нет,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,k6RHevbLAIlGpNoPvOoWdJj9lC9gBwLpXLUp9lCO0A3fB4...,6.294803e+08,NaN,NaN,NaN,NaN,тестировщик с нуля,google,NaN,Search - QA - EU,cpc,loc_interest_ms-__loc_physical_ms-9043353__dev...,NaN,NaN,NaN,NaN,;;;;;;;;;;;;;;;;;;

In [ ]:
df_clean['ID'].duplicated().sum()

np.int64(0)

In [ ]:
df_clean['Lead sale ₴'] = pd.to_numeric(df['Lead sale ₴'], errors='coerce')

/tmp/ipykernel_3245/2748740793.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['Lead sale ₴'] = pd.to_numeric(df['Lead sale ₴'], errors='coerce')

In [ ]:
df_clean['Lead sale ₴'] = df_clean['Lead sale ₴'].astype(float)

/tmp/ipykernel_3245/616112823.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['Lead sale ₴'] = df_clean['Lead sale ₴'].astype(float)

In [ ]:
print(df_clean['Respons. user'].unique())

['Vasyl F.' 'Oksana B.' 'Natalia H.']

In [ ]:
print(df_clean['Modified by'].unique())

['Vasyl F.' 'Oksana B.' 'Natalia H.' 'Ivan M.' nan]

In [ ]:
print(df_clean['Modified on'].unique())

['04.06.2026 10:06:57' '03.06.2026 12:36:49' '03.06.2026 14:31:42'
 '03.06.2026 13:55:08' '03.06.2026 16:55:37' '01.06.2026 10:02:30'
 '03.06.2026 16:38:52' '01.06.2026 10:03:03' '01.06.2026 12:02:13'
 '01.06.2026 12:02:54' '01.06.2026 16:04:54' '29.05.2026 10:49:58'
 '30.05.2026 19:07:10' '29.05.2026 12:12:52' '31.05.2026 16:31:52'
 '03.06.2026 16:57:00' '28.05.2026 15:14:42' '28.05.2026 15:17:39'
 '28.05.2026 16:57:34' '01.06.2026 18:06:09' '03.06.2026 18:24:22'
 '27.05.2026 13:36:21' '28.05.2026 12:53:02' '02.06.2026 11:27:21'
 '25.05.2026 11:40:28' '25.05.2026 15:02:57' '25.05.2026 12:08:08'
 '25.05.2026 12:20:35' '25.05.2026 12:23:20' '25.05.2026 12:24:28'
 '25.05.2026 10:20:58' '28.05.2026 16:57:19' '22.05.2026 12:04:13'
 '22.05.2026 11:54:01' '21.05.2026 18:17:29' '28.05.2026 19:09:44'
 '21.05.2026 15:59:07' '22.05.2026 12:56:31' '26.05.2026 11:01:04'
 '25.05.2026 17:10:47' '27.05.2026 18:39:14' '25.05.2026 16:46:47'
 '21.05.2026 12:57:51' '01.06.2026 18:25:44' '22.05.2026 15:11:04'
 '26.05.2026 15:36:40' '25.05.2026 16:51:47' '26.05.2026 15:20:52'
 '22.05.2026 18:16:24' '25.05.2026 16:58:02' '03.06.2026 16:34:21'
 '25.05.2026 17:21:57' '25.05.2026 17:20:40' '25.05.2026 16:59:50'
 '25.05.2026 17:05:08' '21.05.2026 12:44:34' '30.05.2026 18:18:39'
 '03.06.2026 17:00:58' '21.05.2026 15:48:40' '18.05.2026 19:07:09'
 '19.05.2026 16:17:38' '19.05.2026 13:12:14' '18.05.2026 10:08:43'
 '15.05.2026 17:41:43' '18.05.2026 11:17:14' '03.06.2026 18:48:40'
 '29.05.2026 20:56:58' '14.05.2026 20:00:10' '18.05.2026 19:24:56'
 '13.05.2026 10:33:15' '14.05.2026 19:06:52' '11.05.2026 15:48:41'
 '02.06.2026 20:23:55' '11.05.2026 10:21:55' '11.05.2026 10:15:35'
 '11.05.2026 15:15:47' '15.05.2026 14:48:57' '11.05.2026 15:07:57'
 '22.05.2026 10:36:43' '07.05.2026 17:21:05' '18.05.2026 18:41:09'
 '06.05.2026 15:07:32' '05.05.2026 17:16:35' '12.05.2026 19:05:05'
 '05.05.2026 10:05:15' '05.05.2026 00:29:30' '05.05.2026 10:28:27'
 '05.05.2026 10:28:10' '04.05.2026 20:58:26' '04.05.2026 16:10:53'
 '04.05.2026 10:05:45' '06.05.2026 15:57:33' '06.05.2026 15:53:50'
 '04.05.2026 10:38:53' '04.05.2026 10:30:58' '06.05.2026 15:55:22'
 '06.05.2026 15:54:25' '04.05.2026 10:56:13' '04.05.2026 10:56:27'
 '04.05.2026 10:07:54' '01.05.2026 15:07:56' '01.05.2026 12:47:01'
 '13.05.2026 10:43:07' '05.05.2026 15:22:47' '30.04.2026 16:43:59'
 '01.05.2026 15:41:34' '08.05.2026 15:27:54' '29.04.2026 15:39:14'
 '30.04.2026 16:39:55' '30.04.2026 16:23:24' '28.04.2026 12:07:08'
 '30.04.2026 17:24:47' '28.04.2026 16:08:24' '04.05.2026 16:04:26'
 '27.04.2026 12:32:53' '27.04.2026 12:03:58' '27.04.2026 10:39:30'
 '29.04.2026 14:07:11' '27.04.2026 14:58:48' '27.04.2026 10:34:31'
 '27.04.2026 12:35:11' '04.05.2026 18:56:42' '24.04.2026 14:33:27'
 '27.04.2026 17:16:10' '01.06.2026 14:52:32' '01.05.2026 17:44:54'
 '27.04.2026 15:27:04' '23.04.2026 18:19:55' '26.04.2026 16:18:24'
 '27.04.2026 18:56:52' '15.05.2026 16:13:28' '22.04.2026 10:09:21'
 '27.05.2026 10:32:57' '21.04.2026 17:12:45' '21.04.2026 15:59:45'
 '21.04.2026 10:07:42' '03.06.2026 18:38:17' '20.04.2026 10:19:18'
 '20.04.2026 09:30:43' '21.04.2026 17:36:47' '21.04.2026 17:37:48'
 '20.04.2026 09:31:04' '20.04.2026 09:33:24' '17.04.2026 10:44:18'
 '16.04.2026 12:39:15' '16.04.2026 09:59:49' '15.04.2026 14:41:57'
 '15.04.2026 10:17:31' '20.04.2026 15:25:45' '13.04.2026 10:09:50'
 '13.04.2026 10:25:16' '13.04.2026 10:09:33' '13.04.2026 10:24:21'
 '13.04.2026 10:16:09' '13.04.2026 10:27:26' '21.04.2026 19:02:44'
 '10.04.2026 14:12:58' '14.04.2026 19:01:54' '09.04.2026 18:49:14'
 '20.04.2026 16:20:58' '09.04.2026 08:36:27' '09.04.2026 08:35:23'
 '25.05.2026 10:27:20' '10.04.2026 14:29:06' '08.04.2026 15:58:49'
 '08.04.2026 09:02:01' '07.04.2026 23:03:28' '07.04.2026 10:32:41'
 '13.04.2026 16:54:48' '21.04.2026 19:01:01' '08.04.2026 11:04:27']

In [ ]:
print(df_clean['utm_source'].unique())

[nan]

In [ ]:
print(df_clean['utm_medium'].unique())

[nan]

In [ ]:
print(df_clean['utm_campaign'].unique())

[nan]

In [ ]:
print(df_clean['utm_term'].unique())

[nan]

In [ ]:
print(df_clean['utm_content'].unique())

[nan]

In [ ]:
columns_to_drop = ['utm_source', 'utm_medium', 'utm_campaign', 'utm_term', 'utm_content']

In [ ]:
df_clean.drop(columns=columns_to_drop, inplace=True)
df_clean

/tmp/ipykernel_3327/3196811218.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean.drop(columns=columns_to_drop, inplace=True)

,ID,Lead title,Lead sale ₴,Respons. user,Created on,Created by,Modified on,Modified by,Closed at,Tags,Note,Note 2,Note 3,Note 4,Note 5,Lead stage,Pipeline,Fullname,Contact`s company,Contact respons. user,Lead's company,Work phone,Work DD phone,Mobile phone,Fax,Home phone,Other phone,Work email,Personal email,Other email,Telegram,Position,Skype,ICQ,Jabber,Google Talk,MSN,Other IM,Facebook URL,Пользовательское соглашение,Title,TRAF_SRC,TRAF_TYPE,ADV_CAMP,KEYWORD,TRAF_CONT,GOOGLE_ID,Upcoming Appointment,Оплата,Курс,Lead scoring,Название пакета,Язык,Комментарий,COURSE,UTM_ID,UTM_ADGROUP,FORMNAME,URL первого визита,Referrer,ip,hostname,city,region,country,loc,org,day_of_week,TRAF_SRC.1,GOOGLE_ID.1,TRAF_CONT.1,KEYWORD.1,ADV_CAMP.1,TRAF_TYPE.1,UTM_TARGET,REFERER,FORMID,TRANID,COOKIES,Вопрос 1,Вопрос 2,Вопрос 3,Вопрос 4,Вопрос 5,openstat_campaign,fbclid,yclid,gclid,gclientid,openstat_source,openstat_ad,from,openstat_service,utm_term.1,utm_source.1,referrer,utm_campaign.1,utm_medium.1,utm_content.1,utm_referrer,_ym_uid,_ym_counter,roistat,ga_utm;;;;;;;;;;;;;;;;;;
44,63407150,Lead #63407150,0.0,Vasyl F.,04.06.2026 09:29:40,NaN,04.06.2026 10:06:57,Vasyl F.,not closed,NaN,NaN,NaN,NaN,NaN,NaN,Заявка,Продажи,Serhii Moskalenko,NaN,Vasyl F.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Нет,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,;;;;;;;;;;;;;;;;;;
575,63349437,380734324457,0.0,Oksana B.,03.06.2026 12:33:46,NaN,03.06.2026 12:36:49,Oksana B.,03.06.2026 12:36:00,Ringostat Automation,NaN,NaN,NaN,NaN,NaN,Закрыто и не реализовано (спам),Продажи,Mykola Kravchenko,NaN,Oksana B.,NaN,NaN,NaN,+380979402003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Нет,NaN,C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,;;;;;;;;;;;;;;;;;;
615,63348663,Lead #63348663,0.0,Oksana B.,03.06.2026 11:40:29,NaN,03.06.2026 14:31:42,Oksana B.,not closed,lang-ru,NaN,NaN,NaN,NaN,NaN,Принимает решение,Продажи,Nadiia Bondarenko,NaN,Oksana B.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Monobank частями,QA-тестирование,A,NaN,RU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.849458e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,;;;;;;;;;;;;;;;;;;
1226,63300203,Lead #63300203,0.0,Natalia H.,02.06.2026 13:14:24,NaN,03.06.2026 13:55:08,Natalia H.,03.06.2026 13:55:00,lang-ua,NaN,NaN,NaN,NaN,NaN,Закрыто и не реализовано (перестал отвечать в ...,Продажи,Nadiia Zakharchenko,NaN,Natalia H.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Нет,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,;;;;;;;;;;;;;;;;;;
1712,63234121,Lead #63234121,0.0,Oksana B.,31.05.2026 16:10:06,NaN,03.06.2026 16:55:37,Oksana B.,not closed,NaN,NaN,NaN,NaN,NaN,NaN,Получил материалы,Продажи,Iryna Melnyk,NaN,Oksana B.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Нет,NaN,B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,;;;;;;;;;;;;;;;;;;
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5864,59397093,Lead #59397093,0.0,Oksana B.,07.04.2026 16:19:02,NaN,07.04.2026 23:03:28,Oksana B.,07.04.2026 23:03:00,NaN,NaN,NaN,NaN,NaN,NaN,Закрыто и не реализовано (спам),Продажи,Halyna Boychuk,NaN,Oksana B.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Нет,NaN,C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,;;;;;;;;;;;;;;;;;;
5868,59353455,380960149495,0.0,Natalia H.,06.04.2026 20:41:51,NaN,07.04.2026 10:32:41,Natalia H.,07.04.2026 10:32:00,Ringostat Automation,співпраця,NaN,NaN,NaN,NaN,Закрыто и не реализовано (спам),Продажи,Andrii Boychuk,NaN,Natalia H.,NaN,NaN,NaN,+380632084410,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Нет,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,;;;;;;;;;;;;;;;;;;
5869,59353143,Lead #59353143,0.0,Oksana B.,06.04.2026 20:33:30,NaN,13.04.2026 16:54:48,Oksana B.,13.04.2026 16:54:00,lang-ru,NaN,NaN,NaN,NaN,NaN,Закрыто и не реализовано (не актуально),Продажи,Larysa Kovalenko,NaN,Oksana B.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Нет,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,v6mQmVCllbKtexRgp-NwJJJCNn2VN5b6W8kLP-BgZY8srA...,2.797536e+08,NaN,NaN,NaN,NaN,курс data engineer,google,NaN,Search - Курс Data Analytics - EU,cpc,loc_interest_ms-__loc_physical_ms-9197880__dev...,NaN,NaN,NaN,NaN,;;;;;;;;;;;;;;;;;;
5882,59320181,Lead #59320181,0.0,Vasyl F.,06.04.2026 10:44:45,NaN,21.04.2026 19:01:01,Vasyl F.,21.04.2026 19:01:00,lang-ua,NaN,NaN,NaN,NaN,NaN,Закрыто и не реализовано (перестал отвечать в ...,Продажи,Hryhorii Moskalenko,NaN,Vasyl F.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Нет,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.886348e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,;;;;;;;;;;;;;;;;;;
5883,59318911,Lead #59318911,0.0,Natalia H.,06.04.2026 09:02:13,NaN,08.04.2026 11:04:27,Natalia H.,08.04.2026 11:04:00,lang-ru,NaN,NaN,NaN,NaN,NaN,Закрыто и не реализовано (перестал отвечать в ...,Продажи,Dmytro Moskalenko,NaN,Natalia H.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Нет,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,k6RHevbLAIlGpNoPvOoWdJj9lC9gBwLpXLUp9lCO0A3fB4...,6.294803e+08,NaN,NaN,NaN,NaN,тестировщик с нуля,google,NaN,Search - QA - EU,cpc,loc_interest_ms-__loc_physical_ms-9043353__dev...,NaN,NaN,NaN,NaN,;;;;;;;;;;;;;;;;;;

In [ ]:
df_clean.rename(columns={
    'utm_source.1': 'utm_source',
    'utm_medium.1': 'utm_medium',
    'utm_campaign.1': 'utm_campaign',
    'utm_term.1': 'utm_term',
    'utm_content.1': 'utm_content'
}, inplace=True)
df_clean

/tmp/ipykernel_3327/787997786.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean.rename(columns={

,ID,Lead title,Lead sale ₴,Respons. user,Created on,Created by,Modified on,Modified by,Closed at,Tags,Note,Note 2,Note 3,Note 4,Note 5,Lead stage,Pipeline,Fullname,Contact`s company,Contact respons. user,Lead's company,Work phone,Work DD phone,Mobile phone,Fax,Home phone,Other phone,Work email,Personal email,Other email,Telegram,Position,Skype,ICQ,Jabber,Google Talk,MSN,Other IM,Facebook URL,Пользовательское соглашение,Title,TRAF_SRC,TRAF_TYPE,ADV_CAMP,KEYWORD,TRAF_CONT,GOOGLE_ID,Upcoming Appointment,Оплата,Курс,Lead scoring,Название пакета,Язык,Комментарий,COURSE,UTM_ID,UTM_ADGROUP,FORMNAME,URL первого визита,Referrer,ip,hostname,city,region,country,loc,org,day_of_week,TRAF_SRC.1,GOOGLE_ID.1,TRAF_CONT.1,KEYWORD.1,ADV_CAMP.1,TRAF_TYPE.1,UTM_TARGET,REFERER,FORMID,TRANID,COOKIES,Вопрос 1,Вопрос 2,Вопрос 3,Вопрос 4,Вопрос 5,openstat_campaign,fbclid,yclid,gclid,gclientid,openstat_source,openstat_ad,from,openstat_service,utm_term,utm_source,referrer,utm_campaign,utm_medium,utm_content,utm_referrer,_ym_uid,_ym_counter,roistat,ga_utm;;;;;;;;;;;;;;;;;;
44,63407150,Lead #63407150,0.0,Vasyl F.,04.06.2026 09:29:40,NaN,04.06.2026 10:06:57,Vasyl F.,not closed,NaN,NaN,NaN,NaN,NaN,NaN,Заявка,Продажи,Serhii Moskalenko,NaN,Vasyl F.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Нет,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,;;;;;;;;;;;;;;;;;;
575,63349437,380734324457,0.0,Oksana B.,03.06.2026 12:33:46,NaN,03.06.2026 12:36:49,Oksana B.,03.06.2026 12:36:00,Ringostat Automation,NaN,NaN,NaN,NaN,NaN,Закрыто и не реализовано (спам),Продажи,Mykola Kravchenko,NaN,Oksana B.,NaN,NaN,NaN,+380979402003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Нет,NaN,C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,;;;;;;;;;;;;;;;;;;
615,63348663,Lead #63348663,0.0,Oksana B.,03.06.2026 11:40:29,NaN,03.06.2026 14:31:42,Oksana B.,not closed,lang-ru,NaN,NaN,NaN,NaN,NaN,Принимает решение,Продажи,Nadiia Bondarenko,NaN,Oksana B.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Monobank частями,QA-тестирование,A,NaN,RU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.849458e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,;;;;;;;;;;;;;;;;;;
1226,63300203,Lead #63300203,0.0,Natalia H.,02.06.2026 13:14:24,NaN,03.06.2026 13:55:08,Natalia H.,03.06.2026 13:55:00,lang-ua,NaN,NaN,NaN,NaN,NaN,Закрыто и не реализовано (перестал отвечать в ...,Продажи,Nadiia Zakharchenko,NaN,Natalia H.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Нет,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,;;;;;;;;;;;;;;;;;;
1712,63234121,Lead #63234121,0.0,Oksana B.,31.05.2026 16:10:06,NaN,03.06.2026 16:55:37,Oksana B.,not closed,NaN,NaN,NaN,NaN,NaN,NaN,Получил материалы,Продажи,Iryna Melnyk,NaN,Oksana B.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Нет,NaN,B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,;;;;;;;;;;;;;;;;;;
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5864,59397093,Lead #59397093,0.0,Oksana B.,07.04.2026 16:19:02,NaN,07.04.2026 23:03:28,Oksana B.,07.04.2026 23:03:00,NaN,NaN,NaN,NaN,NaN,NaN,Закрыто и не реализовано (спам),Продажи,Halyna Boychuk,NaN,Oksana B.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Нет,NaN,C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,;;;;;;;;;;;;;;;;;;
5868,59353455,380960149495,0.0,Natalia H.,06.04.2026 20:41:51,NaN,07.04.2026 10:32:41,Natalia H.,07.04.2026 10:32:00,Ringostat Automation,співпраця,NaN,NaN,NaN,NaN,Закрыто и не реализовано (спам),Продажи,Andrii Boychuk,NaN,Natalia H.,NaN,NaN,NaN,+380632084410,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Нет,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,;;;;;;;;;;;;;;;;;;
5869,59353143,Lead #59353143,0.0,Oksana B.,06.04.2026 20:33:30,NaN,13.04.2026 16:54:48,Oksana B.,13.04.2026 16:54:00,lang-ru,NaN,NaN,NaN,NaN,NaN,Закрыто и не реализовано (не актуально),Продажи,Larysa Kovalenko,NaN,Oksana B.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Нет,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,v6mQmVCllbKtexRgp-NwJJJCNn2VN5b6W8kLP-BgZY8srA...,2.797536e+08,NaN,NaN,NaN,NaN,курс data engineer,google,NaN,Search - Курс Data Analytics - EU,cpc,loc_interest_ms-__loc_physical_ms-9197880__dev...,NaN,NaN,NaN,NaN,;;;;;;;;;;;;;;;;;;
5882,59320181,Lead #59320181,0.0,Vasyl F.,06.04.2026 10:44:45,NaN,21.04.2026 19:01:01,Vasyl F.,21.04.2026 19:01:00,lang-ua,NaN,NaN,NaN,NaN,NaN,Закрыто и не реализовано (перестал отвечать в ...,Продажи,Hryhorii Moskalenko,NaN,Vasyl F.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Нет,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.886348e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,;;;;;;;;;;;;;;;;;;
5883,59318911,Lead #59318911,0.0,Natalia H.,06.04.2026 09:02:13,NaN,08.04.2026 11:04:27,Natalia H.,08.04.2026 11:04:00,lang-ru,NaN,NaN,NaN,NaN,NaN,Закрыто и не реализовано (перестал отвечать в ...,Продажи,Dmytro Moskalenko,NaN,Natalia H.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Нет,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,k6RHevbLAIlGpNoPvOoWdJj9lC9gBwLpXLUp9lCO0A3fB4...,6.294803e+08,NaN,NaN,NaN,NaN,тестировщик с нуля,google,NaN,Search - QA - EU,cpc,loc_interest_ms-__loc_physical_ms-9043353__dev...,NaN,NaN,NaN,NaN,;;;;;;;;;;;;;;;;;;

In [ ]:
df_clean['ga_utm;;;;;;;;;;;;;;;;;;'].unique()

array([';;;;;;;;;;;;;;;;;;', ';;', ';', ';;;;', nan, ';;;;;;', ';;;;;'],
      dtype=object)

In [ ]:
df_clean.drop(columns='ga_utm;;;;;;;;;;;;;;;;;;', inplace=True)

/tmp/ipykernel_3245/3303846724.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean.drop(columns='ga_utm;;;;;;;;;;;;;;;;;;', inplace=True)

In [ ]:
df_clean_sale = df_clean[df_clean['Lead sale ₴']>0]
df_clean_sale

,ID,Lead title,Lead sale ₴,Respons. user,Created on,Created by,Modified on,Modified by,Closed at,Tags,Note,Note 2,Note 3,Note 4,Note 5,Lead stage,Pipeline,Fullname,Contact`s company,Contact respons. user,Lead's company,Work phone,Work DD phone,Mobile phone,Fax,Home phone,Other phone,Work email,Personal email,Other email,Telegram,Position,Skype,ICQ,Jabber,Google Talk,MSN,Other IM,Facebook URL,Пользовательское соглашение,Title,TRAF_SRC,TRAF_TYPE,ADV_CAMP,KEYWORD,TRAF_CONT,GOOGLE_ID,Upcoming Appointment,Оплата,Курс,Lead scoring,Название пакета,Язык,Комментарий,COURSE,UTM_ID,UTM_ADGROUP,FORMNAME,URL первого визита,Referrer,ip,hostname,city,region,country,loc,org,day_of_week,TRAF_SRC.1,GOOGLE_ID.1,TRAF_CONT.1,KEYWORD.1,ADV_CAMP.1,TRAF_TYPE.1,UTM_TARGET,REFERER,FORMID,TRANID,COOKIES,Вопрос 1,Вопрос 2,Вопрос 3,Вопрос 4,Вопрос 5,openstat_campaign,fbclid,yclid,gclid,gclientid,openstat_source,openstat_ad,from,openstat_service,utm_term,utm_source,referrer,utm_campaign,utm_medium,utm_content,utm_referrer,_ym_uid,_ym_counter,roistat,ga_utm;;;;;;;;;;;;;;;;;;
3856,62884053,Lead #62884053,5000.0,Oksana B.,24.05.2026 12:42:07,NaN,25.05.2026 15:02:57,Ivan M.,not closed,da-online,в ведомость внесла,NaN,NaN,NaN,NaN,Получили квитанцию,Продажи,Natalia Zakharchenko,NaN,Oksana B.,NaN,'+380631325326,NaN,NaN,NaN,NaN,NaN,rxovdw760@ukr.net,NaN,NaN,@cool_616d3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Монобанк ФОП - Новый,Data Analytics - online,A,Basic,UA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,;;;;;;;;;;;;;;;;;;

In [ ]:
df_clean['utm_campaign'].unique()

array([nan, 'pmax_ai_ua', 'Search - QA - EU', 'Search- Курс AI - UA',
       'pmax_python_ua',
       'HTTP | Data Analytics + безкоштовний курс | Site_Leads | TOF | 22.05',
       'da_free_course_v2', 'pmax_python_eu', 'Search- Курс AI - EU',
       'ai_auto_present', 'search_kursy_eu', 'search_kursy_ua', 'pmax_ua',
       'test_1', 'pmax_eu', 'Search - DevOps - Ukraine',
       'Search - Курс Data Analytics - Ukraine', 'qa_060426',
       'da_free_course_v1', 'Search - Курс Data Analytics - EU'],
      dtype=object)

In [ ]:
df_clean['utm_term'].unique()

array([nan, 'обучение qa engineer с нуля', 'курсы по ии',
       'курсы тестировщика', 'статика 3', 'курс по штучному інтелекту',
       'n8n курс', 'курсы пайтон', 'курси пайтон', 'школа тестировщиков',
       'devops курси', 'data science курс', 'devops engineer обучение',
       'курс data engineer', 'тестировщик с нуля'], dtype=object)

In [ ]:
df_clean['utm_medium'].unique()

array([nan, 'cpc', 'broadcast', 'channel', 'forum', 'bio'], dtype=object)

In [ ]:
df_clean['utm_source'].unique()

array([nan, 'google', 'fb-insta', 'email', 'telegram', 'chatgpt.com',
       'perplexity', 'dou', 'instagram'], dtype=object)

In [ ]:
df_clean['utm_content'].unique()

array([nan, 'loc_interest_ms-__loc_physical_ms-9061060__device-m',
       'loc_interest_ms-__loc_physical_ms-1030409__device-m',
       'loc_interest_ms-__loc_physical_ms-1011430__device-m',
       'broad interests',
       'loc_interest_ms-__loc_physical_ms-9199197__device-m',
       'loc_interest_ms-__loc_physical_ms-9044714__device-m',
       '806220262713', '806220262710', '806220262692',
       'loc_interest_ms-__loc_physical_ms-9067414__device-m',
       'loc_interest_ms-__loc_physical_ms-9256967__device-m',
       'loc_interest_ms-__loc_physical_ms-1012852__device-m',
       'loc_interest_ms-__loc_physical_ms-9194283__device-m',
       'loc_interest_ms-__loc_physical_ms-9197880__device-m',
       'loc_interest_ms-__loc_physical_ms-9043353__device-m'],
      dtype=object)

In [ ]:
df_clean['utm_source'] = df_clean['utm_source'].fillna('not set')
df_clean

/tmp/ipykernel_3245/1395015279.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['utm_source'] = df_clean['utm_source'].fillna('not set')

,ID,Lead title,Lead sale ₴,Respons. user,Created on,Created by,Modified on,Modified by,Closed at,Tags,Note,Note 2,Note 3,Note 4,Note 5,Lead stage,Pipeline,Fullname,Contact`s company,Contact respons. user,Lead's company,Work phone,Work DD phone,Mobile phone,Fax,Home phone,Other phone,Work email,Personal email,Other email,Telegram,Position,Skype,ICQ,Jabber,Google Talk,MSN,Other IM,Facebook URL,Пользовательское соглашение,Title,TRAF_SRC,TRAF_TYPE,ADV_CAMP,KEYWORD,TRAF_CONT,GOOGLE_ID,Upcoming Appointment,Оплата,Курс,Lead scoring,Название пакета,Язык,Комментарий,COURSE,UTM_ID,UTM_ADGROUP,FORMNAME,URL первого визита,Referrer,ip,hostname,city,region,country,loc,org,day_of_week,TRAF_SRC.1,GOOGLE_ID.1,TRAF_CONT.1,KEYWORD.1,ADV_CAMP.1,TRAF_TYPE.1,UTM_TARGET,REFERER,FORMID,TRANID,COOKIES,Вопрос 1,Вопрос 2,Вопрос 3,Вопрос 4,Вопрос 5,openstat_campaign,fbclid,yclid,gclid,gclientid,openstat_source,openstat_ad,from,openstat_service,utm_term,utm_source,referrer,utm_campaign,utm_medium,utm_content,utm_referrer,_ym_uid,_ym_counter,roistat
44,63407150,Lead #63407150,0,Vasyl F.,04.06.2026 09:29:40,NaN,04.06.2026 10:06:57,Vasyl F.,not closed,NaN,NaN,NaN,NaN,NaN,NaN,Заявка,Продажи,Serhii Moskalenko,NaN,Vasyl F.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Нет,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,not set,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
575,63349437,380734324457,0,Oksana B.,03.06.2026 12:33:46,NaN,03.06.2026 12:36:49,Oksana B.,03.06.2026 12:36:00,Ringostat Automation,NaN,NaN,NaN,NaN,NaN,Закрыто и не реализовано (спам),Продажи,Mykola Kravchenko,NaN,Oksana B.,NaN,NaN,NaN,+380979402003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Нет,NaN,C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,not set,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
615,63348663,Lead #63348663,0,Oksana B.,03.06.2026 11:40:29,NaN,03.06.2026 14:31:42,Oksana B.,not closed,lang-ru,NaN,NaN,NaN,NaN,NaN,Принимает решение,Продажи,Nadiia Bondarenko,NaN,Oksana B.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Monobank частями,QA-тестирование,A,NaN,RU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.849458e+08,NaN,NaN,NaN,NaN,NaN,not set,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1226,63300203,Lead #63300203,0,Natalia H.,02.06.2026 13:14:24,NaN,03.06.2026 13:55:08,Natalia H.,03.06.2026 13:55:00,lang-ua,NaN,NaN,NaN,NaN,NaN,Закрыто и не реализовано (перестал отвечать в ...,Продажи,Nadiia Zakharchenko,NaN,Natalia H.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Нет,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,not set,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1712,63234121,Lead #63234121,0,Oksana B.,31.05.2026 16:10:06,NaN,03.06.2026 16:55:37,Oksana B.,not closed,NaN,NaN,NaN,NaN,NaN,NaN,Получил материалы,Продажи,Iryna Melnyk,NaN,Oksana B.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Нет,NaN,B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,not set,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5864,59397093,Lead #59397093,0,Oksana B.,07.04.2026 16:19:02,NaN,07.04.2026 23:03:28,Oksana B.,07.04.2026 23:03:00,NaN,NaN,NaN,NaN,NaN,NaN,Закрыто и не реализовано (спам),Продажи,Halyna Boychuk,NaN,Oksana B.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Нет,NaN,C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,not set,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5868,59353455,380960149495,0,Natalia H.,06.04.2026 20:41:51,NaN,07.04.2026 10:32:41,Natalia H.,07.04.2026 10:32:00,Ringostat Automation,співпраця,NaN,NaN,NaN,NaN,Закрыто и не реализовано (спам),Продажи,Andrii Boychuk,NaN,Natalia H.,NaN,NaN,NaN,+380632084410,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Нет,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,not set,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5869,59353143,Lead #59353143,0,Oksana B.,06.04.2026 20:33:30,NaN,13.04.2026 16:54:48,Oksana B.,13.04.2026 16:54:00,lang-ru,NaN,NaN,NaN,NaN,NaN,Закрыто и не реализовано (не актуально),Продажи,Larysa Kovalenko,NaN,Oksana B.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Нет,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,v6mQmVCllbKtexRgp-NwJJJCNn2VN5b6W8kLP-BgZY8srA...,2.797536e+08,NaN,NaN,NaN,NaN,курс data engineer,google,NaN,Search - Курс Data Analytics - EU,cpc,loc_interest_ms-__loc_physical_ms-9197880__dev...,NaN,NaN,NaN,NaN
5882,59320181,Lead #59320181,0,Vasyl F.,06.04.2026 10:44:45,NaN,21.04.2026 19:01:01,Vasyl F.,21.04.2026 19:01:00,lang-ua,NaN,NaN,NaN,NaN,NaN,Закрыто и не реализовано (перестал отвечать в ...,Продажи,Hryhorii Moskalenko,NaN,Vasyl F.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Нет,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.886348e+08,NaN,NaN,NaN,NaN,NaN,not set,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5883,59318911,Lead #59318911,0,Natalia H.,06.04.2026 09:02:13,NaN,08.04.2026 11:04:27,Natalia H.,08.04.2026 11:04:00,lang-ru,NaN,NaN,NaN,NaN,NaN,Закрыто и не реализовано (перестал отвечать в ...,Продажи,Dmytro Moskalenko,NaN,Natalia H.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Нет,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,k6RHevbLAIlGpNoPvOoWdJj9lC9gBwLpXLUp9lCO0A3fB4...,6.294803e+08,NaN,NaN,NaN,NaN,тестировщик с нуля,google,NaN,Search - QA - EU,cpc,loc_interest_ms-__loc_physical_ms-9043353__dev...,NaN,NaN,NaN,NaN

In [ ]:
df_clean['utm_content'] = df_clean['utm_content'].fillna('not set')

/tmp/ipykernel_3245/63685036.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['utm_content'] = df_clean['utm_content'].fillna('not set')

In [ ]:
df_clean['utm_term'] = df_clean['utm_term'].fillna('not set')

/tmp/ipykernel_3245/760818835.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['utm_term'] = df_clean['utm_term'].fillna('not set')

In [ ]:
df_clean['utm_medium'] = df_clean['utm_medium'].fillna('not set')

/tmp/ipykernel_3245/2177508337.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['utm_medium'] = df_clean['utm_medium'].fillna('not set')

In [ ]:
df_clean['utm_source'] = df_clean['utm_source'].fillna('not set')

/tmp/ipykernel_3245/3379618113.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['utm_source'] = df_clean['utm_source'].fillna('not set')

In [ ]:
df_clean['utm_campaign'] = df_clean['utm_campaign'].fillna('not set')

/tmp/ipykernel_3245/3191573807.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['utm_campaign'] = df_clean['utm_campaign'].fillna('not set')

In [ ]:
df_clean['utm_source'] = df_clean['utm_source'].str.lower()

/tmp/ipykernel_3245/3432243357.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['utm_source'] = df_clean['utm_source'].str.lower()

In [ ]:
df_clean['utm_source'] = df_clean['utm_source'].str.replace('fb-insta', 'facebook', case=False)

/tmp/ipykernel_3245/819471355.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['utm_source'] = df_clean['utm_source'].str.replace('fb-insta', 'facebook', case=False)

In [ ]:
df_clean['Курс'].unique()

array([nan, 'QA-тестирование', 'Data Analytics - online', 'Java - очно',
       'DevOps', 'AI Automation'], dtype=object)

In [ ]:
df_clean['Modified on'] = pd.to_datetime(df_clean['Modified on'], dayfirst=True, errors='coerce')

/tmp/ipykernel_3245/2768511333.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['Modified on'] = pd.to_datetime(df_clean['Modified on'], dayfirst=True, errors='coerce')

In [ ]:
df_clean['Created on'] = pd.to_datetime(df_clean['Created on'], dayfirst=True, errors='coerce')

/tmp/ipykernel_3245/540604958.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['Created on'] = pd.to_datetime(df_clean['Created on'], dayfirst=True, errors='coerce')

In [ ]:
df_clean['Closed at'] = pd.to_datetime(df_clean['Closed at'], dayfirst=True, errors='coerce')

/tmp/ipykernel_3245/3805131007.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_clean['Closed at'] = pd.to_datetime(df_clean['Closed at'], dayfirst=True, errors='coerce')
/tmp/ipykernel_3245/3805131007.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['Closed at'] = pd.to_datetime(df_clean['Closed at'], dayfirst=True, errors='coerce')

In [ ]:
df_clean['Year'] = df_clean['Created on'].dt.year

/tmp/ipykernel_3245/2990181063.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['Year'] = df_clean['Created on'].dt.year

In [ ]:
df_clean['Month number'] = df_clean['Created on'].dt.month

/tmp/ipykernel_3245/1841087623.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['Month number'] = df_clean['Created on'].dt.month

In [ ]:
df_clean['Month name'] = df_clean['Created on'].dt.month_name

/tmp/ipykernel_3245/1748961130.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['Month name'] = df_clean['Created on'].dt.month_name

In [ ]:
df_clean['Week Number'] = df_clean['Created on'].apply(lambda x: int(x.strftime('%W')) if pd.notna(x) else None)

/tmp/ipykernel_3245/799010172.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['Week Number'] = df_clean['Created on'].apply(lambda x: int(x.strftime('%W')) if pd.notna(x) else None)

In [ ]:
df_clean['Quarter'] = df_clean['Created on'].dt.quarter

/tmp/ipykernel_3245/1103178229.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['Quarter'] = df_clean['Created on'].dt.quarter

In [ ]:
df_clean.to_csv("crm_cleaned.csv", index=False, encoding="utf-8-sig")